include:
  - project: "GNOME/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
  BUNDLE: "org.gnome.Showtime.Devel.flatpak"
  MANIFEST_PATH: "build-aux/flatpak/org.gnome.Showtime.Devel.json"
  FLATPAK_MODULE: "showtime"
  APP_ID: "org.gnome.Showtime.Devel"
  RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

flatpak@x86_64:
  extends: ".flatpak@x86_64"
  interruptible: true

flatpak@aarch64:
  extends: ".flatpak@aarch64"
  allow_failure: true
  interruptible: true

nightly@x86_64:
  extends: ".publish_nightly"
  stage: deploy
  dependencies:
    - flatpak@x86_64

nightly@aarch64:
  extends: ".publish_nightly"
  stage: deploy
  dependencies:
    - flatpak@aarch64
